### PR TITLE
Use redis connection pool

### PR DESCRIPTION
**Pull request by jamescasbon**
Its a pull request this time.

### CODE REVIEW

**Comment by sc68cal** [comment]
Just a bit of a nit here - but I was trying to figure out how I could have made such a serious mistake, to the point that
the plugin `goes wrong after a certain number of open connections.`

It appears that this was not the case.

``` python
import bottle
import bottle_redis


app = bottle.Bottle()
plugin = bottle_redis.RedisPlugin(host="localhost")
app.install(plugin)

@app.route("/show/:item")
def show(item,rdb):
    return rdb.get(item)
```

```
[1317] 22 Feb 01:17:03 - Accepted 127.0.0.1:65329
[1317] 22 Feb 01:17:03 - Client closed connection
[1317] 22 Feb 01:17:04 - 0 clients connected (0 slaves), 922304 bytes in use
[1317] 22 Feb 01:17:06 - Accepted 127.0.0.1:65331
[1317] 22 Feb 01:17:06 - Client closed connection
[1317] 22 Feb 01:17:08 - Accepted 127.0.0.1:65333
[1317] 22 Feb 01:17:08 - Client closed connection
```

Now obviously, lots of opening and closing connections is not so great. Your fix does keep a persistent connection, improving performance

```
[1297] 22 Feb 01:13:49 - Accepted 127.0.0.1:65303
[1297] 22 Feb 01:13:51 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:13:56 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:01 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:06 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:11 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:16 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:21 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:26 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:31 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:36 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:41 - 1 clients connected (0 slaves), 930896 bytes in use
[1297] 22 Feb 01:14:46 - 1 clients connected (0 slaves), 930896 bytes in use
```

**Comment by jamescasbon** [comment]
Oh, sorry.  I wasn't clear.  I meant goes wrong after a certain number of _concurrent_ connections.  Where goes wrong means that connections start being refused by redis IIRC.  

You can see the motivation here: http://casbon.me/what-will-pypy-do-for-your-website-benchmarki

**Comment by sc68cal** [comment]
> Oh, sorry. I wasn't clear. I meant goes wrong after a certain number of concurrent connections. 

Ah. Indeed that is the case. Thank you for the clarification! Excellent work all around :cake:

**Comment by waawal** [comment]
Shouldn't the pool be created in the setup-method instead of the apply?

**Comment by sc68cal** [comment]
`setup` is used to do some bottle specific housekeeping, mostly making sure there isn't a keyword conflict. There's nothing to stop you from putting it in the `setup` function, it's just that by convention, all the real action has happened in the `apply` function.

@defnull may have a better explanation, based on what Bottle does internally when hooking up a plugin.

**Comment by defnull** [comment]
`setup` is called once per plugin and is used to prepare the plugin. I would create the pool there.
`apply` is called one per plugin and route-callback and is used to do route-specific stuff. If you want to have support for different pools based on the route, then you should create the pool there.

**Comment by sc68cal** [comment]
Thanks for the clarification @defnull - I'll made that change. Thanks for the suggestion @waawal

**Pull request merged**
